# linux
SYSCONFDIR=	/etc
SBINDIR=	/bin
LIBDIR=		/lib
LIBEXECDIR=	/lib/dhcpcd
DBDIR=		/var/lib/dhcpcd
RUNDIR=		/var/run/dhcpcd
LIBDIR=		/lib
MANDIR=		/usr/share/man
DATADIR=	/usr/share
CPPFLAGS+=	-DHAVE_CONFIG_H
CFLAGS+=	-g -Wall -Wextra -Wundef
CFLAGS+=	-Wmissing-prototypes -Wmissing-declarations
CFLAGS+=	-Wmissing-format-attribute -Wnested-externs
CFLAGS+=	-Winline -Wcast-align -Wcast-qual -Wpointer-arith
CFLAGS+=	-Wreturn-type -Wswitch -Wshadow
CFLAGS+=	-Wcast-qual -Wwrite-strings
CFLAGS+=	-Wformat=2
CFLAGS+=	-Wpointer-sign -Wmissing-noreturn
CFLAGS+=	-Wredundant-decls
CFLAGS+=	-Wconversion
CFLAGS+=	-Wstrict-overflow
CFLAGS+=	-Wlogical-op
CPPFLAGS+=	-D_GNU_SOURCE
CPPFLAGS+=	-D_FILE_OFFSET_BITS=64
CPPFLAGS+=	-D_LARGEFILE_SOURCE
CPPFLAGS+=	-D_LARGEFILE64_SOURCE
DHCPCD_SRCS+=	if-linux.c
CKSUM=		sha256sum --tag
PGP=		gpg2
DEFAULT_HOSTNAME=		(none)
CPPFLAGS+=	-DINET
DHCPCD_SRCS+=	dhcp.c ipv4.c bpf.c
CPPFLAGS+=	-DARP
DHCPCD_SRCS+=	arp.c
CPPFLAGS+=	-DARPING
CPPFLAGS+=	-DIPV4LL
DHCPCD_SRCS+=	ipv4ll.c
CPPFLAGS+=	-DINET6
DHCPCD_SRCS+=	ipv6.c ipv6nd.c
CPPFLAGS+=	-DDHCP6
DHCPCD_SRCS+=	dhcp6.c
CPPFLAGS+=	-DAUTH
SRCS+=		auth.c
PRIVSEP_SRCS=
CC=		/home/moebius/eclipse2/ignored/target/x86_64/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc
DHCPCD_SRCS+=	dhcpcd-embedded.c
COMPAT_SRCS+=	compat/closefrom.c
COMPAT_SRCS+=	compat/arc4random.c
COMPAT_SRCS+=	compat/arc4random_uniform.c
COMPAT_SRCS+=	compat/pidfile.c
COMPAT_SRCS+=	compat/setproctitle.c
COMPAT_SRCS+=	compat/strtoi.c compat/strtou.c
VENDOR_SRCS+=	vendor/rbtree.c
RBTREE_CPPFLAGS+=	-DRBLOCAL
RBTREE_CPPFLAGS+=	"-D__unused=__attribute__((__unused__))"
RBTREE_CPPFLAGS+=	"-D__predict_false(exp)=__builtin_expect((exp) ? 1 : 0, 0)"
MD5_SRC=	compat/crypt/md5.c
SHA256_SRC=	compat/crypt/sha256.c
HMAC_SRC=	compat/crypt/hmac.c
CRYPT_SRCS+=	${HMAC_SRC}
CRYPT_SRCS+=	${MD5_SRC}
CRYPT_SRCS+=	${SHA256_SRC}
SERVICEEXISTS=	
SERVICECMD=	
SERVICESTATUS=	
STATUSARG=	
HOOKSCRIPTS=	50-ntp.conf
EGHOOKSCRIPTS=	50-yp.conf
